### ISSUE TITLE
Incompatible with Portable Scanner Mod

### ISSUE THREAD

**Issue by 6135** [Eryux/supermarketsim-storedelivery#1]
Whenever using the portable scanner mod, it's functions become unusable.

**Comment by Eryux** [comment]
I checked for portable scanner mod, of what it does and how it does it shouldn't be a problem to have both in the same time but this is just the code analysis because in-game I was never able to make portable scanner work as intended even without any mod.

What I experienced with portable scanner (with or without StoreDelivery) :
- The mod load correctly
- When I start a game, if I scan a label it play an error sound (that is normal because I need to open market app on computer first)
- After opening the market app, scanning a label doesn't do anything
